# -*- coding: utf-8 -*-
"""BMI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16PuAFlNrWQEOmrJqY04EcWeqFu0XXM6s
"""

h = float(input("請輸入您的身高(公尺):"))
w = float(input("請輸入你的體重(公斤):"))

BMI = w / (h ** 2)

print(f"您的BMI是:{BMI:.2f}")

